//
// CharacterList.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct CharacterList: Codable {

    public var info: Info
    public var results: [CharacterModel]

    public init(info: Info, results: [CharacterModel]) {
        self.info = info
        self.results = results
    }

}
