//
// LivingStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public enum LivingStatus: String, Codable, CaseIterable {
    case dead = "dead"
    case alive = "alive"
    case unknown = "unknown"
}
